# Generated by Django 5.2.1 on 2025-05-19 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_myuser_groups_myuser_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 19, 12, 33, 59, 693183, tzinfo=datetime.timezone.utc)),
        ),
    ]
